[project]
name = "nps-senti-ml"
version = "0.1.0"
description = "Machine learning utilities for the NPS sentiment project"
requires-python = ">=3.12"
dependencies = [
    "nps-senti-core",
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv.sources]
"nps-senti-core" = { workspace = true }
