[project]
name = "nps-senti-core"
version = "0.1.0"
description = "Core configuration and utilities for the NPS sentiment pipelines"
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
