on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI

jobs:  
  check_style_python:
    name: Check file formatting and style (Python)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install 3.14
      - name: Sync deps
        run: uv sync --locked --dev

      - name: Ruff
        run: |
          uv run ruff check .
          uv run ruff format --check .

      - name: Pyright
        run: uv run pyright

  test_python:
    name: Tests (Python)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install 3.14
      - name: Sync deps
        run: uv sync --locked --dev

      - name: Run tests
        run: uv run python -m pytest -v
